name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
      - uses: sksat/action-clippy@v0.7.0
        with:
          reporter: github-pr-review
          github_token: ${{ github.token }}
      # - uses: giraffate/clippy-action@v1
      #   with:
      #     reporter: 'github-pr-review'
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - uses: dtolnay/rust-toolchain@nightly
      
    - name: Build
      run: cargo build
      
    - name: Run tests
      run: cargo test
