name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # - uses: auguwu/clippy-action@1.4.0
      #   with:
      #     token: ${{secrets.GITHUB_TOKEN}}
          
      # - uses: sksat/action-clippy@v1.1.1
      #   if: github.event_name == 'push'
      #   with:
      #     reporter: github-check
      #     level: info

      # - uses: sksat/action-clippy@v1.1.1
      #   if: github.event_name == 'pull_request'
      #   with:
      #     reporter: github-pr-review
      #     level: info
          
      # - uses: giraffate/clippy-action@v1
      #   with:
      #     reporter: 'github-pr-review'
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - uses: dtolnay/rust-toolchain@nightly
      
    - name: Build
      run: cargo build
      
    - name: Run tests
      run: cargo test
